import type {NextPage} from 'next';
import Head from 'next/head';
import Form from '../components/Form';
import Hero from '../components/Hero';

const Home: NextPage = () => {
    return (
        <div>
          <div className="container mx-auto">
            <Head>
                <title>Feedback</title>
                <meta name="description" content="Generated by Feedback" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero/>
            <Form/>
            <div className="grid grid-cols-1 xl:grid-cols-3 gap-5 mt-10 mb-10 auto-rows-min">
              <div className="py-4 px-3 bg-gray-300 rounded text-md font-medium font-rubik text-slate-600 shadow-lg hover:shadow-gray-400 hover:scale-105 duration-500 cursor-pointer tracking-wide">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum consectetur ducimus quisquam ea. Eveniet est asperiores nihil necessitatibus fugit expedita atque architecto cum ipsum veritatis? Dolor a deserunt nulla amet!
              </div>
              <div className="py-4 px-3 bg-gray-300 rounded text-md font-medium font-rubik text-slate-600 shadow-lg hover:shadow-gray-400 hover:scale-105 duration-500 cursor-pointer tracking-wide">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum consectetur ducimus quisquam ea. Eveniet est asperiores nihil necessitatibus fugit expedita atque architecto cum ipsum veritatis? Dolor a deserunt nulla amet!
              </div>
              <div className="py-4 px-3 bg-gray-300 rounded text-md font-medium font-rubik text-slate-600 shadow-lg hover:shadow-gray-400 hover:scale-105 duration-500 cursor-pointer tracking-wide">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum consectetur ducimus quisquam ea. Eveniet est asperiores nihil necessitatibus fugit expedita atque architecto cum ipsum veritatis? Dolor a deserunt nulla amet!
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum consectetur ducimus quisquam ea. Eveniet est asperiores nihil necessitatibus fugit expedita atque architecto cum ipsum veritatis? Dolor a deserunt nulla amet!
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum consectetur ducimus quisquam ea. Eveniet est asperiores nihil necessitatibus fugit expedita atque architecto cum ipsum veritatis? Dolor a deserunt nulla amet!
              </div>
              <div className="py-4 px-3 bg-gray-300 rounded text-md font-medium font-rubik text-slate-600 shadow-lg hover:shadow-gray-400 hover:scale-105 duration-500 cursor-pointer tracking-wide">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum consectetur ducimus quisquam ea. Eveniet est asperiores nihil necessitatibus fugit expedita atque architecto cum ipsum veritatis? Dolor a deserunt nulla amet!
              </div>
              <div className="py-4 px-3 bg-gray-300 rounded text-md font-medium font-rubik text-slate-600 shadow-lg hover:shadow-gray-400 hover:scale-105 duration-500 cursor-pointer tracking-wide">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum consectetur ducimus quisquam ea. Eveniet est asperiores nihil necessitatibus fugit expedita atque architecto cum ipsum veritatis? Dolor a deserunt nulla amet!
              </div>
            </div>
          </div>
        </div>
    );
};

export default Home;
