import type {NextPage} from 'next';
import Head from 'next/head';
import Comment from '../components/Comment';
import Form from '../components/Form';
import Hero from '../components/Hero';

const Home: NextPage = () => {
    return (
        <div className="bg-[#f7fafc]">
            <div className="container mx-auto">
                <Head>
                    <title>Feedback</title>
                    <meta name="description" content="Generated by Feedback" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Hero/>
                <Form/>
                <Comment />
            </div>
        </div>
    );
};

export default Home;
