import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Secreto Clone</title>
        <meta name="description" content="Generated by Secreto Clone" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center my-10'>
        <h1 className="text-3xl font-bold underline text-blue-600">Next Js</h1>
      </div>
    </div>
  )
}

export default Home
